#!/bin/bash
start=`date +%s`
echo "Running restart..."
docker-compose down && docker volume prune -f && docker-compose up -d
end=`date +%s`
echo -e "\nScript has reached its end after: " $((end-start)) " seconds"
